#include<stdio.h>
#include<pthread.h>
#include<time.h>
#include<stdlib.h>
#include<unistd.h>
#include<semaphore.h>
sem_t mutex,empty,full;
// we will declare three semaphore that we will use in the following code.
static int buff=0;
// this is the buffer that we will use.
void *pro()
	{
	//producer function
	while(1)
		{
		sem_wait(&empty);
		//this will decrement the value of empty. As initially the buffer is empty so it is 
		//initialized with 10 every time this command will run it will decrement the value
		sem_wait(&mutex);
		// this will decrement the value of mutex. As it is initialized with 1 will go to 0.          
		//After that no other process will be able to enter as it cannot go beyond 0.
		if(buff<10)
			{
			buff++;
			printf("\nProducer produce item and buffer size now is %d",buff);
			}
		else
			printf("\nBuffer is already full no space left to produce");
			// there is no need to write else part here as sem(&empty) will be a infinite loop
			// so it will never come out unless buffer is small than 10.
		sem_post(&mutex);
		// this will increment the value of mutex to 1. Resulting in the unlocking the 
		//mutex for other processes.
		sem_post(&full);
		// this will increment the value of full as now there is one item in the buffer. So
		//full will be incremented from 0 to 1 initially.
		sleep(1 + rand()%2);
		//this function will let the thread sleep for the time generated by the rand() fun.
		}
	}
void *con()
	{
	//Consumer function
	while(1)
	{
		sem_wait(&full);
		//Since we are consuming the value the Full will be decremented as it represent                          		
		//the Items in the buffer.
		sem_wait(&mutex);
 		// this will decrement the value of mutex. As it is initialized with 1 will go to 0.          
		//After that no other process will be able to enter as it cannot go beyond 0.

		if(buff!=0)
			{
			buff--;
			printf("\nConsumer consumed item remaining item %d",buff);
			}
		else if(buff==0)
			printf("\nbuffer is empty nothing to consume");
			// there is no need to write else part here as sem(&full) will be a infinite 
			//loop unless there is something in the buffer.

		sem_post(&mutex);
		// this will increment the value of mutex to 1. Resulting in the unlocking 
		//the mutex for other processes.

		sem_post(&empty);
		// this will increment the value of empty as now there is one item less in 
		//the buffer. So empty will be incremented from 0 to 1 initially
		sleep(1 + rand()%6);
		//this function will let the thread sleep for the time generated by the rand() 4
		//fun. Note that consumer sleeps time is more than that of Producer.

	}
}
void main()
{
pthread_t p1,c2;
// thread declaration
sem_init(&mutex,2,1);
sem_init(&empty,2,10);
sem_init(&full,2,0);
//semaphore initilization
for(int i=0;;)
	{
	pthread_create(&p1,NULL,pro,NULL);
	pthread_create(&c2,NULL,con,NULL);
	pthread_join(p1,NULL);
	pthread_join(c2,NULL);
	}
//loop for creating and joining the thread.
}
